# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Fetch today's manga+ ranking"

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  fetch-today-ranking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - run: yarn install
    - run: make today
    - uses: zwaldowski/git-commit-action@v1
