name: "Fetch MANGA Plus ranking"

on:
  schedule:
    - cron: "30 15 * * *"
  workflow_dispatch:

jobs:
  fetch-today-ranking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        persist-credentials: true
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - run: yarn install
    - name: Fetch data
      run: make today
    - uses: zwaldowski/git-commit-action@v1
    - uses: ad-m/github-push-action@master
      with:
        ssh: true
        branch: ${{ github.ref }}
