name: Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - name: Install fd
        uses: baptiste0928/cargo-install@v1
        with:
          crate: fd-find
      - name: Install yj
        uses: baptiste0928/cargo-install@v1
        with:
          crage: yj
      - name: Install pip deps
        run: pip install jinja2-cli
      - name: Build sake site
        run: make site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'site/out'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
